### ISSUE TITLE
model.py里面transition_params的trainable状态是否应该改为True

### ISSUE THREAD

**Issue by zhuweida222** [saiwaiyanyu/bi-lstm-crf-ner-tf2.0#2]
否则转移状态矩阵怎么更新呢

**Comment by saiwaiyanyu** [comment]
可以看下
model.py line 37

```
            log_likelihood, self.transition_params = tf_ad.text.crf_log_likelihood(logits, label_sequences, text_lens)
            self.transition_params = tf.Variable(self.transition_params, trainable=False)
```
self.transition_params 可以打印出来，应该会更新的。

**Comment by tbEgg** [comment]
> 可以看下
> model.py line 37
> 
> ```
>             log_likelihood, self.transition_params = tf_ad.text.crf_log_likelihood(logits, label_sequences, text_lens)
>             self.transition_params = tf.Variable(self.transition_params, trainable=False)
> ```
> 
> self.transition_params 可以打印出来，应该会更新的。

这样更新得到的transition_params是每次随机生成的，正确的应该是随着训练过程不断调整的吧？

**Comment by ffy2017** [comment]
同问，这里的transition_params是怎么更新的

**Comment by saiwaiyanyu** [comment]
> > 可以看下
> > model.py line 37
> > ```
> >             log_likelihood, self.transition_params = tf_ad.text.crf_log_likelihood(logits, label_sequences, text_lens)
> >             self.transition_params = tf.Variable(self.transition_params, trainable=False)
> > ```
> > 
> > 
> > self.transition_params 可以打印出来，应该会更新的。
> 
> 这样更新得到的transition_params是每次随机生成的，正确的应该是随着训练过程不断调整的吧？

嗯嗯，发现了，这是一个bug。需要在 crf_log_likelihood 传入 trans 然后进行更新， 已经修改。谢谢提醒

**Comment by saiwaiyanyu** [comment]
> 同问，这里的transition_params是怎么更新的

这里代码有一个bug，需要在 crf_log_likelihood 传入 trans 然后进行更新， 已经修改哈。
